// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// DfmNormalGammaCoefficients
Rcpp::List DfmNormalGammaCoefficients(Rcpp::List object);
RcppExport SEXP _dfmtools_DfmNormalGammaCoefficients(SEXP objectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    rcpp_result_gen = Rcpp::wrap(DfmNormalGammaCoefficients(object));
    return rcpp_result_gen;
END_RCPP
}
// DfmNormalGammaForecasts
Rcpp::List DfmNormalGammaForecasts(Rcpp::List object);
RcppExport SEXP _dfmtools_DfmNormalGammaForecasts(SEXP objectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    rcpp_result_gen = Rcpp::wrap(DfmNormalGammaForecasts(object));
    return rcpp_result_gen;
END_RCPP
}
// DfmNormalGammaLogLik
Rcpp::List DfmNormalGammaLogLik(Rcpp::List object);
RcppExport SEXP _dfmtools_DfmNormalGammaLogLik(SEXP objectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    rcpp_result_gen = Rcpp::wrap(DfmNormalGammaLogLik(object));
    return rcpp_result_gen;
END_RCPP
}
// DfmNormalStochvolCoefficients
Rcpp::List DfmNormalStochvolCoefficients(Rcpp::List object);
RcppExport SEXP _dfmtools_DfmNormalStochvolCoefficients(SEXP objectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    rcpp_result_gen = Rcpp::wrap(DfmNormalStochvolCoefficients(object));
    return rcpp_result_gen;
END_RCPP
}
// DfmNormalStochvolForecasts
Rcpp::List DfmNormalStochvolForecasts(Rcpp::List object);
RcppExport SEXP _dfmtools_DfmNormalStochvolForecasts(SEXP objectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    rcpp_result_gen = Rcpp::wrap(DfmNormalStochvolForecasts(object));
    return rcpp_result_gen;
END_RCPP
}
// DfmNormalStochvolLogLik
Rcpp::List DfmNormalStochvolLogLik(Rcpp::List object);
RcppExport SEXP _dfmtools_DfmNormalStochvolLogLik(SEXP objectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    rcpp_result_gen = Rcpp::wrap(DfmNormalStochvolLogLik(object));
    return rcpp_result_gen;
END_RCPP
}
// DfmTvpGammaCoefficients
Rcpp::List DfmTvpGammaCoefficients(Rcpp::List object);
RcppExport SEXP _dfmtools_DfmTvpGammaCoefficients(SEXP objectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    rcpp_result_gen = Rcpp::wrap(DfmTvpGammaCoefficients(object));
    return rcpp_result_gen;
END_RCPP
}
// DfmTvpGammaForecasts
Rcpp::List DfmTvpGammaForecasts(Rcpp::List object);
RcppExport SEXP _dfmtools_DfmTvpGammaForecasts(SEXP objectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    rcpp_result_gen = Rcpp::wrap(DfmTvpGammaForecasts(object));
    return rcpp_result_gen;
END_RCPP
}
// DfmTvpGammaLogLik
Rcpp::List DfmTvpGammaLogLik(Rcpp::List object);
RcppExport SEXP _dfmtools_DfmTvpGammaLogLik(SEXP objectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    rcpp_result_gen = Rcpp::wrap(DfmTvpGammaLogLik(object));
    return rcpp_result_gen;
END_RCPP
}
// DfmTvpStochvolCoefficients
Rcpp::List DfmTvpStochvolCoefficients(Rcpp::List object);
RcppExport SEXP _dfmtools_DfmTvpStochvolCoefficients(SEXP objectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    rcpp_result_gen = Rcpp::wrap(DfmTvpStochvolCoefficients(object));
    return rcpp_result_gen;
END_RCPP
}
// DfmTvpStochvolForecasts
Rcpp::List DfmTvpStochvolForecasts(Rcpp::List object);
RcppExport SEXP _dfmtools_DfmTvpStochvolForecasts(SEXP objectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    rcpp_result_gen = Rcpp::wrap(DfmTvpStochvolForecasts(object));
    return rcpp_result_gen;
END_RCPP
}
// DfmTvpStochvolLogLik
Rcpp::List DfmTvpStochvolLogLik(Rcpp::List object);
RcppExport SEXP _dfmtools_DfmTvpStochvolLogLik(SEXP objectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    rcpp_result_gen = Rcpp::wrap(DfmTvpStochvolLogLik(object));
    return rcpp_result_gen;
END_RCPP
}
// FavarNormalWishartCoefficients
Rcpp::List FavarNormalWishartCoefficients(Rcpp::List object);
RcppExport SEXP _dfmtools_FavarNormalWishartCoefficients(SEXP objectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    rcpp_result_gen = Rcpp::wrap(FavarNormalWishartCoefficients(object));
    return rcpp_result_gen;
END_RCPP
}
// FavarNormalWishartForecasts
Rcpp::List FavarNormalWishartForecasts(Rcpp::List object);
RcppExport SEXP _dfmtools_FavarNormalWishartForecasts(SEXP objectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    rcpp_result_gen = Rcpp::wrap(FavarNormalWishartForecasts(object));
    return rcpp_result_gen;
END_RCPP
}
// FavarNormalWishartLogLik
Rcpp::List FavarNormalWishartLogLik(Rcpp::List object);
RcppExport SEXP _dfmtools_FavarNormalWishartLogLik(SEXP objectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type object(objectSEXP);
    rcpp_result_gen = Rcpp::wrap(FavarNormalWishartLogLik(object));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dfmtools_DfmNormalGammaCoefficients", (DL_FUNC) &_dfmtools_DfmNormalGammaCoefficients, 1},
    {"_dfmtools_DfmNormalGammaForecasts", (DL_FUNC) &_dfmtools_DfmNormalGammaForecasts, 1},
    {"_dfmtools_DfmNormalGammaLogLik", (DL_FUNC) &_dfmtools_DfmNormalGammaLogLik, 1},
    {"_dfmtools_DfmNormalStochvolCoefficients", (DL_FUNC) &_dfmtools_DfmNormalStochvolCoefficients, 1},
    {"_dfmtools_DfmNormalStochvolForecasts", (DL_FUNC) &_dfmtools_DfmNormalStochvolForecasts, 1},
    {"_dfmtools_DfmNormalStochvolLogLik", (DL_FUNC) &_dfmtools_DfmNormalStochvolLogLik, 1},
    {"_dfmtools_DfmTvpGammaCoefficients", (DL_FUNC) &_dfmtools_DfmTvpGammaCoefficients, 1},
    {"_dfmtools_DfmTvpGammaForecasts", (DL_FUNC) &_dfmtools_DfmTvpGammaForecasts, 1},
    {"_dfmtools_DfmTvpGammaLogLik", (DL_FUNC) &_dfmtools_DfmTvpGammaLogLik, 1},
    {"_dfmtools_DfmTvpStochvolCoefficients", (DL_FUNC) &_dfmtools_DfmTvpStochvolCoefficients, 1},
    {"_dfmtools_DfmTvpStochvolForecasts", (DL_FUNC) &_dfmtools_DfmTvpStochvolForecasts, 1},
    {"_dfmtools_DfmTvpStochvolLogLik", (DL_FUNC) &_dfmtools_DfmTvpStochvolLogLik, 1},
    {"_dfmtools_FavarNormalWishartCoefficients", (DL_FUNC) &_dfmtools_FavarNormalWishartCoefficients, 1},
    {"_dfmtools_FavarNormalWishartForecasts", (DL_FUNC) &_dfmtools_FavarNormalWishartForecasts, 1},
    {"_dfmtools_FavarNormalWishartLogLik", (DL_FUNC) &_dfmtools_FavarNormalWishartLogLik, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_dfmtools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
