// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// post_lambda
arma::mat post_lambda(arma::mat& x, arma::mat& ff, arma::mat& prior_vinv, arma::sp_mat& uinv, arma::mat lambda);
RcppExport SEXP _dfmtools_post_lambda(SEXP xSEXP, SEXP ffSEXP, SEXP prior_vinvSEXP, SEXP uinvSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type ff(ffSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type prior_vinv(prior_vinvSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat& >::type uinv(uinvSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(post_lambda(x, ff, prior_vinv, uinv, lambda));
    return rcpp_result_gen;
END_RCPP
}
// update_Ha
arma::sp_mat update_Ha(arma::mat& a, int& n_factors, int& p, int& tt);
RcppExport SEXP _dfmtools_update_Ha(SEXP aSEXP, SEXP n_factorsSEXP, SEXP pSEXP, SEXP ttSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type a(aSEXP);
    Rcpp::traits::input_parameter< int& >::type n_factors(n_factorsSEXP);
    Rcpp::traits::input_parameter< int& >::type p(pSEXP);
    Rcpp::traits::input_parameter< int& >::type tt(ttSEXP);
    rcpp_result_gen = Rcpp::wrap(update_Ha(a, n_factors, p, tt));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dfmtools_post_lambda", (DL_FUNC) &_dfmtools_post_lambda, 5},
    {"_dfmtools_update_Ha", (DL_FUNC) &_dfmtools_update_Ha, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_dfmtools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
