# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.post_lambda <- function(x, ff, prior_vinv, uinv, lambda) {
    .Call(`_dfmtools_post_lambda`, x, ff, prior_vinv, uinv, lambda)
}

