# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.DfmNormalGammaCoefficients <- function(object) {
    .Call(`_dfmtools_DfmNormalGammaCoefficients`, object)
}

.DfmNormalGammaForecasts <- function(object) {
    .Call(`_dfmtools_DfmNormalGammaForecasts`, object)
}

.DfmNormalGammaLogLik <- function(object) {
    .Call(`_dfmtools_DfmNormalGammaLogLik`, object)
}

.DfmNormalStochvolCoefficients <- function(object) {
    .Call(`_dfmtools_DfmNormalStochvolCoefficients`, object)
}

.DfmNormalStochvolForecasts <- function(object) {
    .Call(`_dfmtools_DfmNormalStochvolForecasts`, object)
}

.DfmNormalStochvolLogLik <- function(object) {
    .Call(`_dfmtools_DfmNormalStochvolLogLik`, object)
}

.DfmTvpGammaCoefficients <- function(object) {
    .Call(`_dfmtools_DfmTvpGammaCoefficients`, object)
}

.DfmTvpGammaForecasts <- function(object) {
    .Call(`_dfmtools_DfmTvpGammaForecasts`, object)
}

.DfmTvpGammaLogLik <- function(object) {
    .Call(`_dfmtools_DfmTvpGammaLogLik`, object)
}

